#!/bin/bash
printf "Acts upon all pdf files in current folder"
printf "Converting all pdf to .txt files\n"

#Use let for basic arithmetic
let i=1

#Using command substitution to replace the command with its result
for item in $(locate *.pdf)
do
    pdftotext $item temp$i.txt
    let i=$i+1
done

printf "Counting word frequencies, ignoring case and punctuation...\n"

#Transliterate, substitues value i in first ' ' with value i in second ' '. In this case, replace every (repeating) space with newline, dot with nothing
#Sort just sorts the stream of words in alphabnumerical order. Appending the -rn flags makes it go with numbers in reversed order
#uniq merges repeated lines from input - the reason we sorted them beforehand. Appending the c-flag makes it count how many merges it does
cat temp*.txt | tr -s ' .,?!:;' '\n' | sort | uniq -ci | sort -n |awk '{print $1, $2}' > results.txt

printf "Cleaning temporary files\n"
rm temp*.txt

printf "Done. Results can be found in results.txt\n"
