#!/bin/bash
printf "Adding: %s\n\n" "Git, setting default credentials"

sudo apt -y install git
git config --global user.name "Laureleo"
git config --global user.email "hugringr@gmail.com"
git config --global push.default simple

mkdir ~/git

printf "Adding: %s\n\n" " New ssh key. Press enter to accept defaults"
ssh-keygen -t rsa -b 4096 -C "hugringr@gmail.com"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
xclip -sel clip < ~/.ssh/id_rsa.pub
python3 -mwebbrowser https://github.com/
printf "%s\n\n" "Key saved to clipboard. Enter settings to add it"


