#!/bin/bash
printf "Checking if KVM can be run\n\n"
sudo apt install -y cpu-checker 
sudo kvm-ok

printf "Installing KVM \n\n"
sudo apt-get -y install qemu-kvm bridge-utils virt-manager

printf "Add user to libvirtd \n\n"
adduser $(whoami) libvirt
systemctl restart libvirtd.service

newgrp libvirt

printf "DONE \n\n"


printf " SOURCES:
\n https://help.ubuntu.com/community/KVM/Installation 
\n https://computingforgeeks.com/use-virt-manager-as-non-root-user/ 
You may have to restart your computer for the changes to take effect\n"


