#!/bin/bash
printf "Baseline Setup Initialized "

printf "Adding: %s\n\n" "colemak"
setxkbmap us -variant colemak

printf "To add fonts, run as sudo"
sudo dpkg --configure -a
sudo apt-get -y update
sudo apt-get -y install
sudo apt-get -y autoremove

printf "Adding: %s\n\n" "Vim and setting it to be default editor"
sudo apt -y install vim
export VISUAL=vim
export EDITOR="$VISUAL"

printf "Adding: %s\n\n" "bashrc and vimrc"
cp ./.bash_aliases ~/
cp ./.vimrc ~/

printf "Adding: %s\n\n" "Xclip"
sudo apt -y install xclip

printf "Adding: %s\n\n" "Vundle"
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

printf "Adding: %s\n\n" "Plugins"
vim +PluginInstall +qall

printf "Adding: %s\n\n" "YCM Packages"
sudo apt -y install build-essential cmake python3-dev

printf "Adding: %s\n\n" "YouCompleteMe"
cd ~/.vim/bundle/YouCompleteMe
python3 install.py --clang-completer
cd ~/

printf "Adding: %s\n\n" "Natural Scroll"
gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll true

printf "Adding: %s\n\n" "Sloppy focus mode for mouse"
gsettings set org.gnome.desktop.wm.preferences focus-mode 'sloppy'

printf "Adding: %s\n\n" "Tap To Click"
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true 

printf "Adding: %s\n\n" "Chromium web browser"
sudo apt -y install chromium-browser

printf "Adding: %s\n\n" "New font: To use source semibold, just enter preferences"
git clone https://github.com/adobe-fonts/source-code-pro.git ~/git/font
mv ~/git/font/OTF/ /usr/share/fonts/opentype
fc-cache -f -v

printf "Adding: %s\n\n" "Default Java JDK"
sudo apt-get -y install default-jdk

printf "Adding: %s\n\n" "VLC, Deluge(torrent)"
sudo apt-get install vlc
sudo apt-get install deluge

printf "%s\n\n" "Setup completed. Enjoy"
gsettings set org.gnome.desktop.background picture-uri file://$(pwd)/bg.jpg

